### ISSUE TITLE
add video links to all papers 2016

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#239]

**Comment by suchow** [comment]
I know it's probably too late at this point, but I recommend changing the SciPy proceedings style so that the link to the video appears at the end of the paper under its own heading, not at the top of the first page. This tries to balance two competing interests: (1) that the talks are a great way to learn about a topic and its useful to be able to find the talk from the PDF, and (2) that reading a paper is hard work and having a link to a YouTube video as the first thing a reader sees is a surefire way to distract the reader away from the paper and lower the probability that it will be read. Furthermore, there is some concern over using YouTube URLs as opposed to some other system like a DOI which is intended to be archival.

**Comment by sbenthall** [comment]
I'm +1 this change in principle but it should be a separate ticket since it is a separate software feature.
We are going to need to triage which software changes are necessary before publication of the 2016 proceedings, as in some cases (see #240 for example) software has been broken, not just distracting.

**Comment by sbenthall** [comment]
Is this ticket complete @sarostru ? If so, please close. thx

**Comment by sarostru** [comment]
It's on the branch https://github.com/scipy-conference/scipy_proceedings/commits/add-videos-2016 , we need to merge this into 2016, closing this as it is moved to a PR, https://github.com/scipy-conference/scipy_proceedings/pull/244 .
