### ISSUE TITLE
Inline syntax highlighting (code role)

### ISSUE THREAD

**Issue by wheerd** [scipy-conference/scipy_proceedings#298]
As discussed in #276, it wuld be nice to have inline syntax highlighting. Docutils already provides a [`code` role](http://docutils.sourceforge.net/docs/ref/rst/roles.html#code) for that:
```
.. role:: py(code)
   :language: py

Here is a example of inline code: :py`a = 5 if b else 42`.
```
Unfortunately, for most of the generated latex commands, no styling is defined so that the syntax hlighlighting is not visible.

Docutils itself generates a bunch of fallback commands, but it would be nice to get the same formatting as for code blocks:
```
%%% Fallback definitions for Docutils-specific commands
% basic code highlight:
\providecommand*\DUrolecomment[1]{\textcolor[rgb]{0.40,0.40,0.40}{#1}}
\providecommand*\DUroledeleted[1]{\textcolor[rgb]{0.40,0.40,0.40}{#1}}
\providecommand*\DUrolekeyword[1]{\textbf{#1}}
\providecommand*\DUrolestring[1]{\textit{#1}}
```
I am not sure where the best place to put custom definitions for that similar to the `PY` ones would be.

**Comment by mpacer** [comment]
If it is transforming back to generated LaTeX commands it's a matter of identifying the tokens and applying styling in the [sphinx_highlight module](https://github.com/scipy-conference/scipy_proceedings/blob/2017/publisher/writer/sphinx_highlight.py).  

What are the sets of tokens that need styling (and what kind of styling?) in order to make these compatible? 

I'm still not sure why the "basic code highlight" commands are *only* added if we include a bibliography.

**Comment by wheerd** [comment]
They come from docutils itself [here](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/writers/latex2e/__init__.py#l558). I think docutils also uses Pygments for highlighting and it inserts these defaults if inline literals with highlighting are used ([relevant code](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/writers/latex2e/__init__.py#l2481)). I think an option would be to override `visit_literal` in the writer or to insert all the necessary definitions in the latex template. The first option is probably better.
