### ISSUE TITLE
ENH: publish DOIs and ISSN

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#332]
To make the unique identifiers for the conference, proceedings, and individual papers easier to find, we may want to include them on the SciPy website. A reasonable strategy might be:

1. Include paper DOIs in bibfile and html page
2. Include proceedings DOI and conference ISSN at http://conference.scipy.org/proceedings/scipy2017/
3. Include conference DOI and ISSN at conference.scipy.org (this will require PR to https://github.com/scipy-conference/conference.scipy.org)

The identifiers themselves end up in the json metadata files while the proceedings are built, so it should be possible to inject them into the tex, html, and/or bibfiles.

**Comment by mbeyeler** [comment]
^ I second that. It would also be nice if the DOI showed up in the rendered PDF of the paper.

**Comment by mpacer** [comment]
@FatihAkici This will be similar to #355 in editing the templates and connecting it to metadata, however, it will likely be easier to address since we are creating the metadata in question. However, we have issues with when the data is being created (see below) 

Right now doi information is only being constructed in `build_papers.py`. Is there a way that we could instead construct it on a per paper basis? What was the reasoning for doing it there instead of inside the individual build_paper step? Otherwise, this is going to require building the proceedings multiple times in order to first create the doi information and then to include it in the papers themselves. 

@deniederhut Could you layout what precursor information is needed to validly build the doi for one paper?

**Comment by deniederhut** [comment]
Sure thing, M! The paper DOI's get built from the info in [scipy_proc.json](https://github.com/scipy-conference/scipy_proceedings/blob/82253931a114463b31856f93169b5a65553eae3a/scipy_proc.json#L3) and three pieces of information that are intended to tie the DOI to the environment where the paper was originally built. These are:

1. The name of the machine building the proceedings; and,
2. The shortened version of the latest commit hash; and,
3. The sequential ordering of each paper (consecutive integers, stored in hexadecimal).

The function that does this is [here](https://github.com/scipy-conference/scipy_proceedings/blob/82253931a114463b31856f93169b5a65553eae3a/publisher/doitools.py#L39). 

[Right now, DOIs are generated after each paper is built, but before the proceedings are built, by reading values out of the compiled toc_entries](https://github.com/scipy-conference/scipy_proceedings/blob/82253931a114463b31856f93169b5a65553eae3a/publisher/build_papers.py#L72).  I don't recall an a priori reason why this must occur _after_ paper builds -- I think it was just easier for me to add this in as a loosely coupled process.

**Comment by deniederhut** [comment]
We should also add this in the html metadata tags  in `publisher/_templates/header.html.tmpl` so it is easier for google scholar to pick up. It would look something close to `<meta name="citation_doi" content="{{article['doi']}}"`.

**Comment by deniederhut** [comment]
Oh, and also in `_templates/article.bib.tmpl`.

**Comment by mpacer** [comment]
If we create the dois after the papers are built, we can't include the dois in the papers themselves. We could include them in the html, but not the pdfs themselves.

**Comment by mpacer** [comment]
What made it easier to do it afterward? Was it adding the dois to an existing json file as opposed to constructing it all at once? or is there some way in which the whole collection of papers plays into the way that dois are generated?

**Comment by deniederhut** [comment]
This was closed in #371
