### ISSUE TITLE
Is it OK to have an author that isn't a "real person"?

### ISSUE THREAD

**Issue by choldgraf** [scipy-conference/scipy_proceedings#374]
The Jupyter project is writing up an article on Binder/BinderHub. The Jupyter [authorship guidelines](https://github.com/jupyter/governance/blob/master/papers.md#author-ordering) use "Project Jupyter" as the first author. Is this OK for SciPy?

**Comment by deniederhut** [comment]
Interesting question. I'm in favor of letting the Jupyter team list their own authors however they feel is equitable, although I will note that I haven't seen project authorship done quite this way before. My recollection is that papers either list the project as:

1. The sole author (e.g. The R Core Team); or,
2. The affiliation of a giant list of authors (I think the connectome project does it this way).

I'm not seeing any obvious reasons not to allow this. @eseiver, could I ask for your input here? @mpacer, will this cause issues with your plans to include ORCID in the future?

**Comment by eseiver** [comment]
Group authorship is definitely a thing, provided for in section two of ICMJE guidelines [here](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html#two).

Do you have the notion of a corresponding author for the proceedings? If so, that person generally has to be a person with an ORCID. For group authorship, it can be the senior member of the group or the person taking direct responsibility for the article. That designation applies at the submission stage but also can apply at publication. As long as there is a single person's email (or several people's emails) associated with the article so a reader can contact the responsible author(s) instead of the entire group, a single group author with no individual corresponding authors should be fine. Of course, that means that there wouldn't be an ORCID associated with the article. There are [working groups](https://orcid.org/content/organization-identifier-working-group) establishing a similar persistent identifier system to ORCID for organizations and groups, but alas that standard doesn't exist yet.

Hope that helps!

**Comment by deniederhut** [comment]
Yes very helpful -- thanks for the expert advice!

I'm going to propose that we permit papers to include their team or project name as first author, with the request that the corresponding author for a paper be a person and not the whole project (this will simplify communication on our end).

Chris, does this sound okay to you?

@dalippa , any objections?

**Comment by choldgraf** [comment]
that seems reasonable to me!

**Comment by dalippa** [comment]
I’m good with that.

Please excuse any typos since iSent this from my iPhone

On May 4, 2018, at 06:41, Dillon Niederhut <notifications@github.com> wrote:

Yes very helpful -- thanks for the expert advice!

I'm going to propose that we permit papers to include their team or project name as first author, with the request that the corresponding author for a paper be a person and not the whole project (this will simplify communication on our end).

Chris, does this sound okay to you?

@dalippa , any objections?

**Comment by deniederhut** [comment]
Therefore be it resolved
