### ISSUE TITLE
latex support?

### ISSUE THREAD

**Issue by jzf2101** [scipy-conference/scipy_proceedings#419]
It would be nice to be able to have the option to submit the paper in LaTeX directly since we're considering moving to bibTeX anyway #163 #412

**Comment by llorracc** [comment]
YES.  My team has probably spent a collective 10 hours figuring out how to convert to RST, which is NOT the native language for scientific papers.  Then we realized that it converts the RST back to a LaTeX document, which is what we were converting from!  

Much more efficient would just to have provided a LaTeX template for us to fill in.

**Comment by deniederhut** [comment]
Thanks for the feedback! I wasn't around when this system was first built, but I think the motivation behind using restructured text was to reduce the barrier to entry for new authors. If you are someone who doesn't already know latex, the prospect can be a little daunting. 

I share your frustration (those tables!) and it's something we'll look into for the next development cycle.

**Comment by llorracc** [comment]
The unfortunate thing is that, in making the use of RST mandatory, you massively INCREASED the barriers to entry for people who DID know how to use LaTeX -- which is most scientists.  One of my team members actually proposed that we give up and not submit because after spending many hours on it none of us had the spare time to push the project over the finish line.  Finally three team members found the time to get it over the finish line.  But, if there had only been a LaTeX template, it would have been at most an hour, and maybe much less.

Thanks for taking these points into consideration for the next development round.

**Comment by jzf2101** [comment]
Our team had a similar experience @llorracc .  A number of us knew LaTeX well and struggled to do things we knew how to do- notably citations.  A big challenge for us was to debug the LaTeX and errors through the rst- since we didn't always know how those errors were being generated.

**Comment by choldgraf** [comment]
> for people who DID know how to use LaTeX -- which is most scientists

My intuition is that this is definitely not true, and there seems to be some data to back it up. E.g., latex use is [*highly* field-dependent](https://www.authorea.com/users/3/articles/107393-how-many-scholarly-articles-are-written-in-latex/_show_article):

![image](https://user-images.githubusercontent.com/1839645/41622315-0ef2efec-73c4-11e8-9f3e-6d539a34d22e.png)

I'm +1 on allowing for a direct Latex build _on top of_ the rST build, but think it'd be a mistake to disallow rST submissions.

**Comment by jzf2101** [comment]
To clarify, I'm not asking LaTeX only, just for LaTeX as an option.

**Comment by jzf2101** [comment]
I would disagree with @choldgraf though on building on top of rST- our group struggled with getting LaTeX do do what we wanted without being able to explicitly write the LaTeX itself.  It would be easier if we could submit the raw LaTeX and not have it compile to rST and back to LaTeX for the final build.

**Comment by choldgraf** [comment]
I'm all for supporting latex as well - was just saying that most people don't know latex. For those who *do* know latex, I can see how this is a better option than rst

**Comment by jzf2101** [comment]
Ah, I misunderstood you comment then.

**Comment by MooersLab** [comment]
The on-line collaborative writing software [Overleaf](http://www.overleaf.com) and ShareLatex make it really easy for nonLaTeX users to prepare documents in LaTeX. Overleaf has several million users in diverse fields. I am aware that LaTeX is growing in popularity in the quantitative social sciences like economics and in finance. I am biochemist. I learned about Overleaf from my daughter who used it in her class projects and to write her senior thesis as an undergraduate in economics. The table presented above is a decade old. It may not accurately represent the current situation.

I have prepared documents in Overleaf with new LaTeX users ranging in age from 20 to 70 years of age. Overleaf makes using LaTeX intuitive and fun! It error message system is better than that found in most text editors. Overleaf's use of git to track changes is superior to tracking changes in Word. Users can flip back and forth between source and rich text with the click of button. I do most of my writing in LaTeX, and I mostly use Overleaf. I will resort to using a text editor when I need access to a snippet library because the main weakness of Overleaf is the lack of support for snippet libraries. 

I strongly endorse the use of LaTeX and providing Overleaf with of a SciPy Proceedings template. I have prepared manuscripts, grant applications, books 1000 page long, and beamer posters and slideshows in Overleaf. I currently have about 200 documents in my Overleaf account. I have been using Overleaf for about three years and LaTeX for about eight years.

**Comment by tgmattso** [comment]
Please ... can't we agree to take LATEX source this year?   Converting my existing Latex paper to a new formating system serves no purpose.  Why are you doing this to us?  This is definitely making me question why I have chosen to bring my work to SciPy.   Please ... change this policy.  Latex is heavily used in many communities.  It should be a choice for SciPy authors.

**Comment by ntjess** [comment]
@mepa @cbcunc @deniederhut @stargaser [Proceeding instructions](https://github.com/scipy-conference/scipy_proceedings#contacting-the-proceedings-co-chairs) indicate pinging co-chairs is the best way to reach out -- apologies if I misinterpreted that statement.

For the 2022 round of submissions, has there been any consideration of allowing LaTeX documents directly? I echo the sentiment above where a prohibitive amount of time would be spent converting our already-LaTeX sources into RST format.

**Comment by ntjess** [comment]
Not to spam the issue with comments, but I found this works quite well:

```rst
.. raw:: latex

    \input{sections/intro}
    \input{sections/background}
    % etc.
```

Citations and figures have no issues for my current document, and the paper header can still be specified in RST.

Is this acceptable as a submission? I recognize the potential downside of poor previews in the github markdown viewer, but hopefully that is a reasonable tradeoff. I can also zip & attach a MWE if you wish.

**Comment by deniederhut** [comment]
> has there been any consideration of allowing LaTeX documents directly?

I was hoping to have this ready for the 2022 conference (you can see a WIP here https://github.com/scipy-conference/scipy_proceedings/pull/679) but there have been a series of issues translating the tables, references, etc. Given that papers are already being submitted, it seems wise not to introduce a new build system at the moment.

> Is this acceptable as a submission?

🤔 probably not? We add custom styling during the conversion from rst, so it's unlikely that your paper would look consistent with the rest of the proceedings if you put the whole thing as a raw latex field. Having said that, I'd be happy to be proven wrong.

**Comment by ntjess** [comment]
@deniederhut apologies for the late reply, it took a minute to get a proof-of-concept draft. Are you able to briefly skim the output PDF to confirm whether styling is appropriate? Source tex files and build script are in my paper repo: https://github.com/ntjess/scipy_proceedings/tree/s3a_paper/papers/221_jessurun

My environment works with the default publisher script run on the main rst file.

If the build fails, I am happy to attach the PDF here/elsewhere (~3MB) but I wanted to confirm the normal creation process works for others apart from me.

Thanks! Please note I have no intention of splitting hairs or adamantly sticking to a latex submission. I can rework an rst-only solution if it's required but as others in the thread mentioned, it would certainly be nice to save on the conversion time.

**Comment by MooersLab** [comment]
@deniederhut Will LaTeX submissions be supported in 2024?

**Comment by deniederhut** [comment]
@mepa I think this might be a question for you

**Comment by scoobies** [comment]
Thanks, @deniederhut!

@MooersLab, yes, we plan to support LaTeX submissions this year.

cc: @cbunc @rowanc1

**Comment by mepa** [comment]
Thanks, @deniederhut!

@MooersLab, yes, we plan to support LaTeX submissions this year.

cc: @cbcunc @rowanc1

**Comment by MooersLab** [comment]
@mepa, Awesome! Thank you very much!!!!

**Comment by rowanc1** [comment]
LaTeX, MyST Markdown, and Jupyter Notebooks (for supplemental materials) were all accepted in 2024!

All produced really nice online articles, as well as beautiful PDFs!

https://proceedings.scipy.org/articles/JXDK4427
![image](https://github.com/user-attachments/assets/f8764c68-2b6b-4fbd-8066-2d6b67d17752)
