### ISSUE TITLE
paper not building and permission denied re: git push

### ISSUE THREAD

**Issue by xtianmcd** [scipy-conference/scipy_proceedings#480]
Hi, 

I am unable to use `git push` from the command line. I am met with this error: `remote: Permission to scipy-conference/scipy_proceedings.git denied to xtianmcd.
fatal: unable to access 'https://github.com/scipy-conference/scipy_proceedings/': The requested URL returned error: 403`, and I have to add the files through the website. 

I believe there is a connection though, because when I ran `make_paper.sh` an attempt to build showed up in the build server. However, the paper will not build. I do get a local pdf that works great, except that the references from my `.bib` file do not show up (may be unrelated?). 

I have tried re-cloning the repo and trying the setup in the README, but no luck. I originally forked the repo on the 2018 branch, since I submitted a paper last year as well. It would not let me re-fork this year. I'm not sure if this has any effect. 

If you have any advice, please let me know! 

Thanks.

**Comment by deniederhut** [comment]
Yup, we won't let you write code directly to the scipy_proceesings repository because that could mess things up for everyone. You'll need to send code changes your own fork, open a pull request, and we'll review that pull request. You can see instructions here:

https://github.com/scipy-conference/scipy_proceedings#getting-a-local-copy-of-the-scipy_proceedings-repo

It's hard to know why you are seeing what you are seeing without knowing the full chain of events, but the local make files that you have do not execute anything on procbuild.scipy.org. 

And yes, I've left a comment on [your PR here](https://github.com/scipy-conference/scipy_proceedings/pull/477#issuecomment-495180629) that there is an issue with your bib file that is causing the build to abort. Is it okay if we keep this conversation inside your PR?

**Comment by xtianmcd** [comment]
Absolutely, thanks very much for your help. I'll respond to these points in the PR and will close this issue!
