### ISSUE TITLE
Put together latex template file for pandoc

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#677]

**Comment by deniederhut** [comment]
Initial attempt here: https://github.com/scipy-conference/scipy_proceedings/pull/679

I have the tables working, but not the figure labels

**Comment by ntjess** [comment]
@deniederhut thanks for putting this together. Eventually, I think it would be great to facilitate some compatibility with Overleaf as well, since the vast majority of LaTeX collaborators I know strongly prefer that tool for writing .tex papers.

You are welcome to review my build script for a POC implementation that pulls overleaf content into the current paper worktree if that is of interest. I found it incredibly valuable for simultaneous editing with my co-authors.
https://github.com/ntjess/scipy_proceedings/blob/bd9005b150e5a2b81269dd003aff82fba844ffa7/papers/221_jessurun/rebuild.py#L47-L82

Note that a more generalized solution can easily pull all content into the folder instead of selected subdirectories.

**Comment by Micky774** [comment]
Just wanted to add that indeed my lab has several first-time-authors submitting to this conference and working w/ rST (and in particular debugging when something went wrong) was painful for them. Currently all the debugging is in terms of the generated `style.tex` file and not obvious for newcomers how to approach that. Some kind of style guide/template for use in Overleaf would be an amazing thing to have, but anything that allows for LaTeX as a paralell option to the rST submission would already be a huge improvement in our experience.

Also we really appreciate the effort you're putting in to continuously make this process smoother @deniederhut!

**Comment by deniederhut** [comment]
> Eventually, I think it would be great to facilitate some compatibility with Overleaf

Cool idea! Yeah right now I think the biggest pain point for most submitters is the requirement to submit in rst, so top development priority for us is opening up submission formats to latex/markdown. I've never used overleaf before - how hard is that integration?

**Comment by ntjess** [comment]
It is backed by a git repo by default, so should be trivial if I had to guess:
![image](https://user-images.githubusercontent.com/23620506/170890477-046a0ed8-b46b-44ae-a57e-5734c01ffd2a.png)

My workflow for this paper was to `git checkout --worktree=<paper/dir> -- <tex-files>` and it went quite nicely. If you had the user configure an Overleaf repo environment variable, the `publisher` script that SciPy is using can simply run a checkout command before compiling the paper.

If you're interested, I can give you access to my Overleaf scipy project's git repo (it's all public anyway) and you can run my sync/build script for yourself to test it out :)

Usage:
```bash
# rebuild.py checks for an "OVERLEAF_CURRENT_REPO" environment variable if "overleaf" doesn't exist
# Or just add the remote yourself first
git remote add overleaf https://overleaf/git/repo.git
cd papers/221_jessurun
python rebuild.py

# Open the Overleaf project and add some text
# ...

# Then, come back to your prompt and run:
python rebuild.py --sync-overleaf
# New output will have all changes without manual syncing required
```

Note that `create_rst_sections()` is only necessary since LaTeX was not a viable format for 2022.

**Comment by ntjess** [comment]
Forgot to add: it should also be minimally intrusive to people already using overleaf, since the git repo is the same as the project url 🙂 No need to even open the side bar if you prefer.
![image](https://user-images.githubusercontent.com/23620506/170890851-f5c28e75-f2a1-4dfe-b848-72f62447cfae.png)

**Comment by gpoore** [comment]
@deniederhut Thanks for all your work with the proceedings this year! It looks like you have already made some good progress on Pandoc support. If more help is needed to finish this for next year, I'm interested. I actually wrote my [2022 proceedings paper](https://github.com/scipy-conference/scipy_proceedings/pull/716/files) in Markdown, and then converted to rST using Pandoc. (Pandoc allows including raw rST in Markdown, so I used that for a few edge cases, and also used Lua filters to create some syntax abbreviations.)

Once Pandoc support is in place, that could allow proceedings papers to be more reproducible. Pandoc supports Jupyter notebooks, Quarto/RMarkdown use Pandoc internally, and I've been working on Pandoc-based executable documents myself with Codebraid.

**Comment by rowanc1** [comment]
PDF template for 2024 is here:

https://github.com/curvenote-templates/scipy

Documentation still needs an update for Scipy Authors, but running `myst build --pdf` will work both locally and on CI.

![image](https://github.com/user-attachments/assets/89f1bdab-389a-44a7-bacc-95377137852f)
