### ISSUE TITLE
Please, create sections for abstract and introduction

### ISSUE THREAD

**Issue by ojemebo** [scipy-conference/scipy_proceedings#736]
Sorry for my late response, Allan Campopiano; I was actually added recently as one of the reviewers for your paper.

Your work is indeed interesting and the topic is great, but please:

1) create a section for the abstract where you can have a summary of your work.....one or two sentences for introduction, one sentence for motivation, one sentence for your adopted method, one sentence for results, and the last sentence for future work 

2) create a labeled section for the introduction where you can clearly state a) the problem your study is attempting to solve, 2) motivation (why you are doing this study), 3) methods you are using to solve this problem

3) Apart from the abstract, all sections and subsections should have labels for reference purposes

4) Do away with the abbreviation "e.g"

**Comment by deniederhut** [comment]
Hi @ojemebo ! The authors won't see these comments, since these are being filed as issues against the whole repository. What we'll want to do is leave a pull request review. In GitHub, you can do this by opening the paper PR, and clicking the "view files" tab

<img width="1066" alt="Screen Shot 2022-06-04 at 5 11 41 PM" src="https://user-images.githubusercontent.com/6868396/172027073-21dad63b-ba8b-4713-b374-b1bc4969af32.png">

If you scroll down, you'll see the paper. If you want to leave feedback about an individual line, you can click the "+" button next to a line, and a comment field will open.

<img width="1065" alt="Screen Shot 2022-06-04 at 5 12 11 PM" src="https://user-images.githubusercontent.com/6868396/172027077-d7f45a2a-8210-4d5e-bd55-13cbab085760.png">

If you want to leave overall or summary feedback, you can do this by clicking the "review changes" button in the upper righthand corner. Thanks!

<img width="1066" alt="Screen Shot 2022-06-04 at 5 12 24 PM" src="https://user-images.githubusercontent.com/6868396/172027079-3c64f444-f317-431a-864d-29d03d39510f.png">
