### ISSUE TITLE
html table format

### ISSUE THREAD

**Issue by AmadiGabriel** [scipy-conference/scipy_proceedings#950]
Html table previews properly on Github but improperly on curvenote web preview.

<img width="1058" alt="Screenshot 2024-06-14 at 10 44 09" src="https://github.com/scipy-conference/scipy_proceedings/assets/78109946/a2667fe9-48a4-448b-8b8a-d20d999662f7">
<img width="1293" alt="Screenshot 2024-06-14 at 10 45 25" src="https://github.com/scipy-conference/scipy_proceedings/assets/78109946/906ad313-0d3c-4b8d-a43c-01fd9f484c46">

**Comment by fwkoch** [comment]
Hey @AmadiGabriel - thank you for raising this issue. It is caused by a bug in the MyST rendering: https://github.com/executablebooks/mystmd/issues/1332 - I'll take a pass at addressing that issue.

In the meantime, if you remove all the blank lines from within your html table, it fixes the build:

![image](https://github.com/scipy-conference/scipy_proceedings/assets/9453731/2592cfe3-bdc3-4884-af81-80a928f714f3)

**Comment by rowanc1** [comment]
I believe this was fixed here:
https://github.com/jupyter-book/mystmd/issues/1332
